### ISSUE TITLE
Was genau kann der Adapter?

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.multicast#6]
Hallo,

was genau kann der Adapter?
Welche IP Adressen muss ich eingeben? Sollte er meinen Yamaha RX-V481 erkennen?

**Comment by DutchmanNL** [comment]
> was genau kann der Adapter?
> Welche IP Adressen muss ich eingeben? Sollte er meinen Yamaha RX-V481 erkennen?

Hi Siggi,

Nein deinen Yamaha wird er nicht erkennen : 
```Have an zero-touch adapter in place to integrate any ethernet device (example : ESP based board eq Wemos D1 mini), like Vansware/Gosound smart plugs or other custom build automation.
```

Er stellt eine API zur Verfügung welche man z.b. mit einem ESP (wemos D1 mini) benutzen kan.
Wir werden demnaest eine binary als Beispiel hochladen zum flachen von sogenannten "Vansware" Steckdosen.

@andiling

**Comment by sigi2345** [comment]
> > was genau kann der Adapter?
> > Welche IP Adressen muss ich eingeben? Sollte er meinen Yamaha RX-V481 erkennen?
> 
> Hi Siggi,
> 
> Nein deinen Yamaha wird er nicht erkennen :
> 
> Er stellt eine API zur Verfügung welche man z.b. mit einem ESP (wemos D1 mini) benutzen kan.
> Wir werden demnaest eine binary als Beispiel hochladen zum flachen von sogenannten "Vansware" Steckdosen.
> 
> @andiling

Ok, Danke. Der Name hat mich ein wenig irritiert. (Ähnlichkeit mit MusicCast Adapter)

**Comment by DutchmanNL** [comment]
> Ok, Danke. Der Name hat mich ein wenig irritiert. (Ähnlichkeit mit MusicCast Adapter)

lol, nee MultiCast ist doch echt was anderes ich mach dan mal hier zu ;)
